name: Destroy Infrastructure

on:
  workflow_dispatch:

jobs:
  process-commit-message:
    runs-on: ubuntu-latest

    steps:
      - name: Set initial Terraform status
        run: echo "TERRAFORM_STATUS=❌ Failed" >> $GITHUB_ENV
 
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Init Terraform
        run: terraform init

      - name: Apply Terraform
        id: destroy
        run: terraform destroy -auto-approve

      - name: Collect status
        id: collect_status
        run: |
          echo "TERRAFORM_STATUS=$([[ '${{ steps.apply.outcome }}' == 'success' ]] && echo '✅ Success')" >> $GITHUB_ENV

      - name: Send Telegram Notification
        if: always()
        uses: cbrgm/telegram-github-action@v1
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          message: |
            *Terraform Destroy Status*: ${{ env.TERRAFORM_STATUS }}
